/**
 * Codex subscription adapter (docs/PROVIDER-LIMITS-PLAN.zh-CN.md §2 Codex).
 *
 * Contract (codex-cli 0.155.1 app-server protocol, verified 2026-09-22 with a
 * read-only live probe; JSON Schema generated by `codex app-server
 * generate-json-schema` and the redacted live sample in the plan doc):
 * the transport returns the `account/rateLimits/read` result object:
 * { accountId?: string|null, ordinaryUsageAllowed?: boolean|null,
 *   rateLimits: RateLimitSnapshot (required),
 *   rateLimitsByLimitId?: Record<string, RateLimitSnapshot>|null }
 * RateLimitSnapshot: { limitId?, limitName?, planType?, primary?: Window|null,
 *   secondary?: Window|null, credits?, ... }
 * Window: { usedPercent: integer (required), resetsAt?: int64 unix SECONDS|null,
 *   windowDurationMins?: int64|null }
 *
 * Normalization rules:
 * - the multi-bucket map is preferred when present and non-empty; otherwise the
 *   backward-compatible single bucket is used as the one bucket;
 * - `primary` and `secondary` are separate windows of one limit; each becomes its
 *   own bucket (`<limitId>:primary` / `<limitId>:secondary`), never merged;
 * - `usedPercent` is the server value; `remainingPercent` is only its display
 *   complement (clamped to 0-100), never used to recompute anything;
 * - `resetsAt` arrives as unix SECONDS and is converted to epoch ms; values
 *   outside a sane seconds range are dropped (unknown, not zeroed);
 * - `windowDurationMins` maps 300→5h, 10080→1wk, 43200→1mo; any other duration
 *   keeps an unknown window rather than a guess;
 * - `planType` (free/go/plus/pro/prolite/team/… enum) becomes the plan label;
 * - a JSON-RPC error envelope is classified by redacted pattern: auth-looking
 *   failures are `needs-auth` (the local codex login governs this source), other
 *   errors are `business-error`; the server message is never echoed;
 * - `credits`, `rateLimitResetCredits`, `ordinaryUsageAllowed` and `accountId`
 *   are intentionally not displayed in this slice (sufficiency/count data, not
 *   amounts) — see the plan's data-semantics section.
 *
 * Credential safety (§7): this adapter never touches Pi credentials. The
 * subprocess reads the local codex login (`~/.codex`) itself, so `prepare` does
 * not resolve or require an API key, and no key material can flow into the
 * process arguments or environment.
 */
import type { QuotaProfile } from "../../config.ts";
import type { QuotaBucket, QuotaHeadersLike, QuotaIssue, QuotaSnapshotData, QuotaWindow } from "../types.ts";
import { adapterIssue, isObject, parseJsonPayload } from "./http.ts";

/** Pseudo-origin of the app-server source; the profile `origin` field (an https
 *  origin contract for HTTP adapters) is rejected for codex. */
export const CODEX_QUOTA_ORIGIN = "app-server:codex";

export interface CodexPrepareInput {
  profile: QuotaProfile;
  auth: unknown;
}

export type CodexPrepareResult =
  | { kind: "process"; command: "codex"; args: readonly ["app-server"] }
  | { kind: "issue"; issue: QuotaIssue };

export interface CodexParseContext {
  now: number;
}

export type CodexParseResult =
  | { kind: "snapshot"; snapshot: QuotaSnapshotData }
  | { kind: "issue"; issue: QuotaIssue };

/** Validate the profile; codex needs no host credential (the subprocess owns its
 *  login), so a missing Pi key is not an issue for this source. */
export function codexPrepare(input: CodexPrepareInput): CodexPrepareResult {
  const { profile } = input;
  if (profile.origin) {
    return adapterIssue("needs-verification", false, "the codex adapter has no https origin; remove the origin field");
  }
  if (profile.source !== "codex-app-server") {
    return adapterIssue("needs-verification", false, "codex requires source codex-app-server");
  }
  return { kind: "process", command: "codex", args: ["app-server"] };
}

const WINDOW_BY_MINUTES: Readonly<Record<number, QuotaWindow>> = Object.freeze({
  300: Object.freeze({ unit: "hour", number: 5 }),
  10080: Object.freeze({ unit: "week", number: 1 }),
  43200: Object.freeze({ unit: "month", number: 1 }),
});

/** Unix-seconds → epoch-ms; out-of-range values stay unknown. */
const resetsAtMs = (value: unknown): number | undefined => {
  if (typeof value !== "number" || !Number.isFinite(value)) return undefined;
  if (value <= 0 || value > 4_102_444_800) return undefined; // Beyond year 2100 in seconds.
  return Math.round(value) * 1_000;
};

const usedPercentOf = (value: unknown): number | undefined => {
  if (typeof value !== "number" || !Number.isFinite(value)) return undefined;
  return Math.min(100, Math.max(0, Math.round(value)));
};

interface NormalizedWindow {
  unit: QuotaWindow["unit"];
  number: number;
  /** False when windowDurationMins was absent or not one of the verified
   *  durations: the bucket then keeps an unknown window instead of a guess. */
  windowKnown: boolean;
  usedPercent?: number;
  remainingPercent?: number;
  resetAt?: number;
}

const normalizeWindow = (raw: unknown): NormalizedWindow | null => {
  if (!isObject(raw)) return null;
  const usedPercent = usedPercentOf(raw.usedPercent);
  if (usedPercent === undefined) return null; // The one required field is absent/invalid.
  const window: NormalizedWindow = { unit: "week", number: 1, usedPercent, remainingPercent: 100 - usedPercent, windowKnown: false };
  const duration = raw.windowDurationMins;
  const mapped = typeof duration === "number" && Number.isFinite(duration) ? WINDOW_BY_MINUTES[Math.round(duration)] : undefined;
  if (mapped) {
    window.unit = mapped.unit;
    window.number = mapped.number;
    window.windowKnown = true;
  }
  const reset = resetsAtMs(raw.resetsAt);
  if (reset !== undefined) window.resetAt = reset;
  return window;
};

/** Map one verified snapshot (multi-bucket member or the single-bucket view).
 *  `buckets` is a mutable accumulator owned by the caller; the snapshot freezes it. */
const snapshotBuckets = (raw: unknown, buckets: QuotaBucket[], counters: { ignored: number }): string => {
  if (!isObject(raw)) { counters.ignored++; return ""; }
  const limitId = typeof raw.limitId === "string" && raw.limitId.length > 0 ? raw.limitId : "codex";
  const primary = normalizeWindow(raw.primary);
  if (primary) buckets.push({ id: `${limitId}:primary`, kind: "quota-percent", window: primary.windowKnown ? { unit: primary.unit, number: primary.number } : null, usedPercent: primary.usedPercent, remainingPercent: primary.remainingPercent, resetAt: primary.resetAt });
  const secondary = normalizeWindow(raw.secondary);
  if (secondary) buckets.push({ id: `${limitId}:secondary`, kind: "quota-percent", window: secondary.windowKnown ? { unit: secondary.unit, number: secondary.number } : null, usedPercent: secondary.usedPercent, remainingPercent: secondary.remainingPercent, resetAt: secondary.resetAt });
  if (!primary && !secondary) counters.ignored++;
  return typeof raw.planType === "string" ? raw.planType : "";
};

/** Normalize one verified response. Transport-level failures are handled by the
 *  caller; this function owns the business and mapping semantics. */
export function codexParse(status: number, headers: QuotaHeadersLike | null, body: string, context: CodexParseContext): CodexParseResult {
  void status;
  void headers;
  void context;
  const parsed = parseJsonPayload(body);
  if (!isObject(parsed)) return adapterIssue("protocol-error", true, "invalid JSON");
  if (parsed.error !== undefined) {
    const error = isObject(parsed.error) ? parsed.error.message : undefined;
    const text = typeof error === "string" ? error.toLowerCase() : "";
    if (/log(?:ged)?[ -]?in|auth|token|unauthorized|forbidden/.test(text)) {
      return adapterIssue("needs-auth", false, "app-server reports the codex login is not usable");
    }
    return adapterIssue("business-error", true, "app-server request error");
  }
  const byId = parsed.rateLimitsByLimitId;
  const buckets: QuotaBucket[] = [];
  const counters = { ignored: 0 };
  let planLabel = "";
  const hasMap = isObject(byId);
  if (hasMap) {
    const entries = Object.entries(byId);
    for (const [, value] of entries.slice(0, 8)) {
      const label = snapshotBuckets(value, buckets, counters);
      if (!planLabel && label) planLabel = label;
    }
    if (entries.length > 8) counters.ignored += entries.length - 8;
  }
  if (buckets.length === 0 && !hasMap) {
    // No multi-bucket view: the single-bucket `rateLimits` is the required field —
    // absent means a protocol violation, present-but-windowless means no data.
    if (!isObject(parsed.rateLimits)) return adapterIssue("protocol-error", true, "missing rateLimits");
    const label = snapshotBuckets(parsed.rateLimits, buckets, counters);
    if (!planLabel && label) planLabel = label;
  }
  if (buckets.length === 0) {
    return adapterIssue("no-data", true, "empty rate limits");
  }
  const snapshot: QuotaSnapshotData = {
    buckets: Object.freeze(buckets),
    planLabel,
    ignoredBuckets: counters.ignored,
    truncated: false,
    partial: false,
  };
  return { kind: "snapshot", snapshot };
}
