/**
 * Deterministic synthetic previews rendered by the production renderer.
 * `scripts/demo.mjs` prints this, `scripts/check.mjs` asserts docs/preview.txt matches it,
 * so a layout change cannot silently drift from the committed preview.
 */
import { HudState } from "../src/state.ts";
import { formatHud } from "../src/render.ts";
import { normalizeConfig } from "../src/config.ts";
import { PASTEL_DARK, PASTEL_LIGHT, THEME_ROLES, HUD_ROLES } from "../src/palette.ts";

const fixture = (overrides = {}) => {
  const state = new HudState("/workspace/pi-hud", { id: "example-model", name: overrides.modelName ?? "Example Model", provider: "demo", contextWindow: 200_000 }, 0);
  state.thinking = "high";
  state.messageEnd({ role: "assistant", stopReason: "stop", usage: { input: 12_000, cacheRead: 75_000, cacheWrite: 0, output: 3_000, cost: { total: 0.042 } } }, 1);
  for (let index = 0; index < 5; index++) state.endTool({ toolCallId: `t${index}`, toolName: "read", isError: index === 4 });
  state.startTool({ toolCallId: "active", toolName: "edit", args: { path: "/workspace/pi-hud/src/state.ts" } });
  state.bridge({ version: 1, source: "demo", kind: "agent", id: "review", status: "running", label: "Review implementation" }, 0);
  state.bridge({ version: 1, source: "demo", kind: "tasks", id: "goal", completed: 3, total: 7, label: "Build Pi HUD" }, 0);
  state.git = { available: true, branch: "main", dirty: true };
  if (overrides.contextRatio) state.contextTokens = Math.round(state.contextWindow * overrides.contextRatio);
  return state.snapshot();
};

const rows = (snapshot, preset, language, width) =>
  formatHud(snapshot, normalizeConfig({ preset, language, color: false }), width).map((row) => row.text);

export function renderPreview() {
  const lines = [];
  const push = (...values) => lines.push(...values);
  push(
    "pi-hud synthetic previews — generated by src/render.ts, no ANSI colors",
    "",
    'Fixture: model "Example Model" + thinking "high"; project "pi-hud"; branch "main*";',
    "context 45% (90k/200k); active tool edit state.ts; tools ✓4 !1; 1 agent;",
    'tasks 3/7 "Build Pi HUD"; cost $0.042; ↑87k ↓3.0k.',
    "Separators are · in Unicode mode and | in ASCII mode.",
    "",
  );
  const balanced = fixture();
  for (const language of ["en", "zh-CN"]) {
    for (const preset of ["minimal", "balanced", "full"]) {
      push(`${language} / ${preset} / 120 columns`);
      push(...rows(balanced, preset, language, 120));
      push("");
    }
  }
  push("width folding (en / balanced)");
  for (const width of [40, 80, 120, 180]) push(`${width} columns: ${rows(balanced, "balanced", "en", width).join("  ⏎  ")}`);
  push("");
  push("narrow identity row (40 columns, long model name, context warning keeps its percentage)");
  for (const [language, ratio] of [["en", 0.45], ["en", 0.96], ["zh-CN", 0.96]]) {
    const narrow = fixture({ modelName: "Claude Sonnet 4.5 (200k)", contextRatio: ratio });
    push(`${language} ${Math.round(ratio * 100)}%: ${rows(narrow, "minimal", language, 40)[0]}`);
  }
  push("");
  push("ASCII mode (en / balanced / 80 columns, same information)");
  push(...formatHud(balanced, normalizeConfig({ preset: "balanced", ascii: true, color: false }), 80).map((row) => row.text));
  push("");
  push("alert scoping (en / balanced / 120 columns, context 96%)");
  push(...rows(fixture({ contextRatio: 0.96 }), "balanced", "en", 120));
  push("Only the context field switches to the error color; model, path and separators keep their roles.");
  push("");
  push("palette roles: role, pastel dark, pastel light, theme token");
  for (const role of HUD_ROLES) push(`${role.padEnd(10)} ${PASTEL_DARK[role]}  ${PASTEL_LIGHT[role]}  ${THEME_ROLES[role]}`);
  push("");
  push("mono and color:false render the same text without any escape sequences.");
  return lines.join("\n") + "\n";
}
