/**
 * Deterministic synthetic previews rendered by the production renderer.
 * `scripts/demo.mjs` prints this, `scripts/check.mjs` asserts docs/preview.txt matches it,
 * so a layout change cannot silently drift from the committed preview.
 */
import { HudState } from "../src/state.ts";
import { formatHud } from "../src/render.ts";
import { formatFooter, formatStatusRows } from "../src/footer.ts";
import { normalizeConfig } from "../src/config.ts";
import { PASTEL_DARK, PASTEL_LIGHT, THEME_ROLES, HUD_ROLES } from "../src/palette.ts";

const fixture = (overrides = {}) => {
  const state = new HudState("/workspace/pi-hud", { id: "example-model", name: overrides.modelName ?? "Example Model", provider: "demo", contextWindow: 200_000 }, 0);
  state.thinking = "high";
  state.messageEnd({ role: "assistant", stopReason: "stop", usage: { input: 12_000, cacheRead: 75_000, cacheWrite: 0, output: 3_000, cost: { total: 0.042 } } }, 1);
  const complete = (name, count, options = {}) => {
    for (let index = 0; index < count; index++) {
      state.startTool({ toolCallId: `${name}-${index}`, toolName: name, args: options.path ? { path: options.path } : undefined });
      state.endTool({ toolCallId: `${name}-${index}`, toolName: name, isError: options.errorIndex === index });
    }
  };
  complete("bash", 15, { errorIndex: 14 });
  complete("edit", 3, { path: "/workspace/pi-hud/src/render.ts" });
  complete("write", 2, { path: "/workspace/pi-hud/docs/preview.txt" });
  complete("read", 1, { path: "/workspace/pi-hud/README.md" });
  state.startTool({ toolCallId: "interrupted", toolName: "bash" });
  state.settle();
  if (overrides.active !== false) state.startTool({ toolCallId: "active", toolName: "edit", args: { path: "/workspace/pi-hud/src/state.ts" } });
  if (overrides.bridge !== false) {
    state.bridge({ version: 1, source: "demo", kind: "agent", id: "review", status: "running", label: "Review implementation" }, 0);
    state.bridge({ version: 1, source: "demo", kind: "tasks", id: "goal", completed: 3, total: 7, label: "Build Pi HUD" }, 0);
  }
  state.git = { available: true, branch: "main", dirty: true };
  if (overrides.contextRatio) state.contextTokens = Math.round(state.contextWindow * overrides.contextRatio);
  return state.snapshot();
};

const rows = (snapshot, preset, language, width, extra = {}) =>
  formatHud(snapshot, normalizeConfig({ preset, language, color: false, ...extra }), width).map((row) => row.text);

/** Synthetic identity cache for the footer surface; a real session fills this from lifecycle events. */
const FOOTER_IDENTITY = Object.freeze({ cwd: "~/opensource/pi-hud", provider: "demo", title: "Compare HUDs", branch: "main", branchDirty: true });
const footerRows = (snapshot, preset, language, width, statuses) => {
  const config = normalizeConfig({ preset, language, color: false });
  const result = formatFooter(snapshot, config, width, FOOTER_IDENTITY).map((row) => row.text);
  result.push(...formatStatusRows(statuses, config, width).map((row) => row.text));
  return result;
};

export function renderPreview() {
  const lines = [];
  const push = (...values) => lines.push(...values);
  push(
    "pi-hud synthetic previews — generated by src/render.ts and src/footer.ts, no ANSI colors",
    "",
    'Fixture: model "Example Model" + thinking "high"; project "pi-hud"; branch "main*";',
    "context 45% (90k/200k); running tool edit state.ts; bounded categories",
    "bash ✓14 !1, edit ✓3, write ✓2, read ✓1 folded into +1; interrupted bash ~1;",
    'cost $0.042; observed usage obs* ↑12k ↓3.0k R75k CH86.2%; bridge agent 1 and tasks 3/7 "Build Pi HUD".',
    "The footer surface adds cached identity (cwd, provider, session title) and the host Git branch;",
    "widget rows are unchanged in count (minimal 1 / balanced 2 / full 3).",
    "Separators are · in Unicode mode and | in ASCII mode.",
    "",
  );
  const balanced = fixture();
  for (const language of ["en", "zh-CN"]) {
    for (const preset of ["minimal", "balanced", "full"]) {
      push(`${language} / ${preset} / 120 columns`);
      push(...rows(balanced, preset, language, 120));
      push("");
    }
  }
  push("width folding (en / balanced)");
  for (const width of [40, 80, 120, 180]) push(`${width} columns: ${rows(balanced, "balanced", "en", width).join("  ⏎  ")}`);
  push("");
  push("narrow identity row (40 columns, long model name, context warning keeps its percentage)");
  for (const [language, ratio] of [["en", 0.45], ["en", 0.96], ["zh-CN", 0.96]]) {
    const narrow = fixture({ modelName: "Claude Sonnet 4.5 (200k)", contextRatio: ratio });
    push(`${language} ${Math.round(ratio * 100)}%: ${rows(narrow, "minimal", language, 40)[0]}`);
  }
  push("");
  push("phase-2 narrow regression (40 columns, zh-CN, 95% context with saturated activity)");
  for (const [language, width] of [["zh-CN", 40], ["zh-CN", 44]]) {
    const busy = fixture({ modelName: "Claude Sonnet 4.5 (200k)", contextRatio: 0.95 });
    push(`${language} ${width} columns:`);
    push(...rows(busy, "full", language, width));
  }
  push("");
  push("no bridge data (en / full / 120 columns): no empty placeholder, the area shows usage only");
  push(...rows(fixture({ bridge: false, active: false }), "full", "en", 120));
  push("");
  push("category overflow (en / balanced / 180 columns): only the top three names, the rest fold");
  push(rows(fixture(), "balanced", "en", 180)[1]);
  push("");
  push("ASCII mode (en / balanced / 120 columns, same information)");
  push(...formatHud(balanced, normalizeConfig({ preset: "balanced", ascii: true, color: false }), 120).map((row) => row.text));
  push("");
  push("alert scoping (en / balanced / 120 columns, context 96%)");
  push(...rows(fixture({ contextRatio: 0.96 }), "balanced", "en", 120));
  push("Only the context field switches to the error color; model, path and separators keep their roles.");
  push("Historical tool failures recolor their own count and mark, never the whole row.");
  push("");
  push("palette roles: role, pastel dark, pastel light, theme token");
  for (const role of HUD_ROLES) push(`${role.padEnd(10)} ${PASTEL_DARK[role]}  ${PASTEL_LIGHT[role]}  ${THEME_ROLES[role]}`);
  push("");
  push("mono and color:false render the same text without any escape sequences.");
  push("");

  const footerStatuses = new Map([[ "pi-goal", "goal active · automatic" ], [ "pi-hud", "surface footer" ]]);
  push(
    "footer surface (surface: footer) — body rows are fixed at minimal 2 / balanced 3 / full 4;" ,
    "extension statuses use a separate bounded area of at most 2 rows, 8 entries and 64 characters each.",
    "",
  );
  for (const language of ["en", "zh-CN"]) {
    for (const preset of ["minimal", "balanced", "full"]) {
      push(`${language} / ${preset} / 120 columns`);
      push(...footerRows(balanced, preset, language, 120));
      push("");
    }
  }
  push("footer width folding (en / balanced)");
  for (const width of [40, 80, 120, 180]) push(`${width} columns: ${footerRows(balanced, "balanced", "en", width).join("  ⏎  ")}`);
  push("");
  push("footer with other-extension statuses (en / balanced / 120 columns, then 40 columns)");
  push(...footerRows(balanced, "balanced", "en", 120, footerStatuses));
  push("");
  push(...footerRows(balanced, "balanced", "en", 40, footerStatuses));
  push("");
  push("footer ASCII mode (en / full / 120 columns, same information)");
  {
    const config = normalizeConfig({ preset: "full", ascii: true, color: false });
    push(...formatFooter(balanced, config, 120, FOOTER_IDENTITY).map((row) => row.text));
    push(...formatStatusRows(footerStatuses, config, 120).map((row) => row.text));
  }
  push("");
  push("footer identity folding (en / balanced): session title folds before the branch, provider and cwd");
  for (const width of [40, 80]) push(`${width} columns: ${footerRows(balanced, "balanced", "en", width)[0]}`);
  push("");
  push("footer unknown data (en / balanced / 120 columns): no usage observed, no cache denominator, unknown cost");
  {
    const fresh = new HudState("/workspace/pi-hud", { id: "example-model", name: "Example Model", provider: "demo", contextWindow: 200_000 }, 0);
    fresh.thinking = "high";
    push(...footerRows(fresh.snapshot(), "balanced", "en", 120));
  }
  push("");
  push("footer 95% context warning keeps its percentage at 40/80 columns (long Chinese model name)");
  {
    const busy = fixture({ modelName: "深度求索中文模型名称特别长版本", contextRatio: 0.95 });
    for (const width of [40, 80, 120]) push(`${width} columns: ${footerRows(busy, "balanced", "zh-CN", width)[1]}`);
  }
  push("");
  push("status area folding (en / balanced / 80 columns, 20 statuses): entries beyond the cap fold into +N");
  {
    const many = new Map();
    for (let index = 0; index < 20; index++) many.set(`ext-${index}`, `status text number ${index}`);
    push(...footerRows(balanced, "balanced", "en", 80, many));
  }
  return lines.join("\n") + "\n";
}
